from enum import Enum


class MessageType(str, Enum):
    EVENT = "event"
    COMMAND = "command"


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderState(str, Enum):
    CREATED = "CREATED"
    SUBMITTING = "SUBMITTING"
    REST_ACCEPTED = "REST_ACCEPTED"
    ACKED = "ACKED"
    WORKING = "WORKING"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    PENDING_CANCEL = "PENDING_CANCEL"
    PENDING_REPLACE = "PENDING_REPLACE"
    CANCELED = "CANCELED"
    REPLACED = "REPLACED"
    REJECTED = "REJECTED"
    RECON_HOLD = "RECON_HOLD"
    BROKEN = "BROKEN"


class Environment(str, Enum):
    PROD = "prod"
    VPS = "vps"


class OperationMode(str, Enum):
    NORMAL = "NORMAL"
    DEGRADED = "DEGRADED"
    EXIT_ONLY = "EXIT_ONLY"
    ENTRY_FROZEN = "ENTRY_FROZEN"
    RECON_MODE = "RECON_MODE"
    KILL_SWITCH = "KILL_SWITCH"


class ErrorCategory(str, Enum):
    HTTP_TRANSPORT_ERROR = "HTTP_TRANSPORT_ERROR"
    BROKER_BUSINESS_ERROR = "BROKER_BUSINESS_ERROR"
    WS_CONTROL_ERROR = "WS_CONTROL_ERROR"
    WS_STREAM_GAP = "WS_STREAM_GAP"
    FIELD_MAPPING_ERROR = "FIELD_MAPPING_ERROR"
    UNKNOWN_BROKER_STATUS = "UNKNOWN_BROKER_STATUS"


class RiskPolicyType(str, Enum):
    GLOBAL_SAFETY = "GLOBAL_SAFETY"
    VENUE = "VENUE"
    ACCOUNT_RISK = "ACCOUNT_RISK"
    INSTRUMENT_RISK = "INSTRUMENT_RISK"
    STRATEGY_CONTROL = "STRATEGY_CONTROL"
    EXECUTION = "EXECUTION"
    PARSING = "PARSING"
    BROKER_AUTH = "BROKER_AUTH"
    BROKER_TRANSPORT = "BROKER_TRANSPORT"
    ENVIRONMENT_ISOLATION = "ENVIRONMENT_ISOLATION"

